name: 'PR Job'
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install python dependencies
        run: make install
      - name: Run lint
        run: make lint-ci
      - name: Run tests
        run: make test
