name: 'Run sync on a schedule'
on:
  schedule:
    - cron: '15 10 * * 6'

  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install rclone
        run: |
            curl -sSL https://rclone.org/install.sh | bash
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Retrieve Google Drive API credentials and generate rclone config
        run: |
          make run ARGS="setup"
      - name: Run rclone sync
        run: |
          rclone sync --config .rclone.conf --dry-run GDrive: AWSS3:${{ secrets.S3_BUCKET_NAME }}/Documents
      - name: Save refreshed Google Drive API credentials
        if: always()
        run: |
          make run ARGS="clean"
